export const environment = {
    production: false,
    apiUrl: 'http://localhost:3001/api/v1', // adjust based on actual backend port/version
    baseUrl: 'http://localhost:3001',
    prjSucRedUrl: 'http://localhost:3001/processFinish?status=1&memberid=',

    dobQuesId: 722, // Production value from legacy config
    emailQuesId: 713, // Production value from legacy config
    recaptchaSiteKey: 'site_key_for_recaptcha',
    dynataCustId: '808',
    psCustId: '811',
    inboxSupId: '94',
    deviceIQKey: 'xxxxxxxxx',
    GA_TRACKING_ID: 'ABCD',
    masterZipAnsKeyObj: {
        DMA_CODE: 'dma',
        DMA_NAME: 'dmaName',
        REGION: 'rgn',
        STATE: 'stName',
        ZIPCODES: 'id'
    },
    surveyClosedMessages: {
        0: { h1: 'Survey Unavailable', h4: 'Sorry, this survey is currently not available.' },
        1: { h1: 'Thank you for trying this survey.', h4: "We're sorry you couldn't finish this survey. Sometimes, surveys look for certain groups or interests, and you might not have been a perfect match." },
        2: { h1: 'Survey Unavailable', h4: 'Sorry, this survey already taken by you.' },
        3: { h1: 'Survey Unavailable', h4: 'mis match of query string data from saved data.' },
        4: { h1: 'Survey Unavailable', h4: 'Sorry, transaction id not exist in query string.' },
        5: { h1: 'Thank you for trying this survey.', h4: 'We’re sorry, but you were not able to complete that survey. When a survey has filled in the number of respondents who fit the goal, it will be closed' }
    },
    questionType: {
        SINGLE_PUNCH: 0,
        MULTI_PUNCH: 1,
        OPEN_END_TEXT: 2,
        NUMERIC_OPEN_END_TEXT: 3
    },
    resrchDefender: {
        getTokenAPI: 'https://prod.rtymgt.com/api/v3/respondents/get_token/',
        activityURL: 'https://prod.resdefio.com/activity',
        activity_range: 24,
        headers: {
            "x-api-key": "MCqV62fJve9lPal9ESRyw77WreU32slr9jkeij4W"
        },
        publishable_key: "ac81b20f-1f54-4dbc-b1e8-468a691a1486",
        xhrFields: {
            'Access-Control-Allow-Methods': 'GET, POST',
            'Access-Control-Allow-Headers': "Access-Control-Allow-Headers, Origin, X-Requested-With, Content-Type, Accept, Authorization",
            'Access-Control-Allow-Credentials': true,
        },
        activityTimeout: 8000,
        getTokenTimeout: 8000,
        enabled: true
    },
    verisoul: {
        enabled: true,
        env: 'sandbox',
        projectId: "0706d458-7d76-4468-b18c-f08b3cbc6d45",
        subdomain: "https://js.verisoul.ai/"
    },
    dynataMinAge: [
        { "cntCode": "AR", "minAge": 18 },
        { "cntCode": "AU", "minAge": 18 },
        { "cntCode": "AT", "minAge": 16 },
        { "cntCode": "BE", "minAge": 16 },
        { "cntCode": "BR", "minAge": 18 },
        { "cntCode": "BG", "minAge": 18 },
        { "cntCode": "CA", "minAge": 19 },
        { "cntCode": "CL", "minAge": 18 },
        { "cntCode": "CN", "minAge": 18 },
        { "cntCode": "CO", "minAge": 18 },
        { "cntCode": "CR", "minAge": 18 },
        { "cntCode": "HR", "minAge": 18 },
        { "cntCode": "CZ", "minAge": 16 },
        { "cntCode": "DK", "minAge": 16 },
        { "cntCode": "DO", "minAge": 18 },
        { "cntCode": "EC", "minAge": 18 },
        { "cntCode": "EG", "minAge": 18 },
        { "cntCode": "EE", "minAge": 18 },
        { "cntCode": "FI", "minAge": 16 },
        { "cntCode": "FR", "minAge": 16 },
        { "cntCode": "DE", "minAge": 16 },
        { "cntCode": "GB", "minAge": 16 },
        { "cntCode": "GR", "minAge": 16 },
        { "cntCode": "GT", "minAge": 18 },
        { "cntCode": "HK", "minAge": 18 },
        { "cntCode": "HU", "minAge": 16 },
        { "cntCode": "IN", "minAge": 18 },
        { "cntCode": "ID", "minAge": 15 },
        { "cntCode": "IE", "minAge": 16 },
        { "cntCode": "IL", "minAge": 18 },
        { "cntCode": "IT", "minAge": 16 },
        { "cntCode": "JP", "minAge": 18 },
        { "cntCode": "KE", "minAge": 18 },
        { "cntCode": "KR", "minAge": 19 },
        { "cntCode": "LV", "minAge": 18 },
        { "cntCode": "LT", "minAge": 18 },
        { "cntCode": "LU", "minAge": 18 },
        { "cntCode": "MY", "minAge": 18 },
        { "cntCode": "MX", "minAge": 18 },
        { "cntCode": "MA", "minAge": 18 },
        { "cntCode": "NL", "minAge": 16 },
        { "cntCode": "NZ", "minAge": 18 },
        { "cntCode": "NG", "minAge": 18 },
        { "cntCode": "NO", "minAge": 16 },
        { "cntCode": "PA", "minAge": 18 },
        { "cntCode": "PH", "minAge": 18 },
        { "cntCode": "PL", "minAge": 16 },
        { "cntCode": "PT", "minAge": 16 },
        { "cntCode": "QA", "minAge": 18 },
        { "cntCode": "RO", "minAge": 18 },
        { "cntCode": "SA", "minAge": 18 },
        { "cntCode": "RS", "minAge": 18 },
        { "cntCode": "SG", "minAge": 21 },
        { "cntCode": "SK", "minAge": 18 },
        { "cntCode": "SI", "minAge": 18 },
        { "cntCode": "ZA", "minAge": 18 },
        { "cntCode": "ES", "minAge": 16 },
        { "cntCode": "SE", "minAge": 16 },
        { "cntCode": "CH", "minAge": 16 },
        { "cntCode": "TW", "minAge": 20 },
        { "cntCode": "TH", "minAge": 20 },
        { "cntCode": "TR", "minAge": 18 },
        { "cntCode": "AE", "minAge": 21 },
        { "cntCode": "US", "minAge": 17 },
        { "cntCode": "UY", "minAge": 18 },
        { "cntCode": "VN", "minAge": 16 }
    ]
};
